### ISSUE TITLE
支持windnows吗？

### ISSUE THREAD

**Issue by guqinglei123** [kingname/EverFlowy#1]
这个是否支持windows 10 ？

**Comment by kingname** [comment]
支持。你在Windows 10上面安装Python 3 即可使用。

**Comment by guqinglei123** [comment]
但是，当我在windows上进行的编译时，出现了这个错误。
![image](https://user-images.githubusercontent.com/25784213/55732385-777adb80-5a4e-11e9-9f0e-976decf96e6a.png)
系统版本：windows 10
python版本：python 3.7.0
json版本：2.0.9

**Comment by guqinglei123** [comment]
outlines_json 为：
`'<!DOCTYPE html>\n<html>\n  <head>\n    <meta http-equiv="X-UA-Compatible" content="chrome=1" /><script type="text/javascript">window.NREUM||(NREUM={}),__nr_require=function(e,n,t){function r(t){if(!n[t]){var o=n[t]={exports:{}};e[t][0].call(o.exports,function(n){var o=e[t][1][n];return r(o||n)},o,o.exports)}return n[t].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o<t.length;o++)r(t[o]);return r}({1:[function(e,n,t){function r(){}function o(e,n,t){return function(){return i(e,[c.now()].concat(u(arguments)),n?null:this,t),n?void 0:this}}var i=e("handle"),a=e(3),u=e(4),f=e("ee").get("tracer"),c=e("loader"),s=NREUM;"undefined"==typeof window.newrelic&&(newrelic=s);var p=["setPageViewName","setCustomAttribute","setErrorHandler","finished","addToTrace","inlineHit","addRelease"],d="api-",l=d+"ixn-";a(p,function(e,n){s[n]=o(d+n,!0,"api")}),s.addPageAction=o(d+"addPageAction",!0),s.setCurrentRouteName=o(d+"routeName",!0),n.exports=newrelic,s.interaction=function(){return(new r).get()};var m=r.prototype={createTracer:function(e,n){var t={},r=this,o="function"==typeof n;return i(l+"tracer",[c.now(),e,t],r),function(){if(f.emit((o?"":"no-")+"fn-start",[c.now(),r,o],t),o)try{return n.apply(this,arguments)}catch(e){throw f.emit("fn-err",[arguments,this,e],t),e}finally{f.emit("fn-end",[c.now()],t)}}}};a("actionText,setName,setAttribute,save,ignore,onEnd,getContext,end,get".split(","),function(e,n){m[n]=o(l+n)}),newrelic.noticeError=function(e,n){"string"==typeof e&&(e=new Error(e)),i("err",[e,c.now(),!1,n])}},{}],2:[function(e,n,t){function r(e,n){if(!o)return!1;if(e!==o)return!1;if(!n)return!0;if(!i)return!1;for(var t=i.split("."),r=n.split("."),a=0;a<r.length;a++)if(r[a]!==t[a])return!1;return!0}var o=null,i=null,a=/Version\\/(\\S+)\\s+Safari/;if(navigator.userAgent){var u=navigator.userAgent,f=u.match(a);f&&u.indexOf("Chrome")===-1&&u.indexOf("Chromium")===-1&&(o="Safari",i=f[1])}n.exports={agent:o,version:i,match:r}},{}],3:[function(e,n,t){function r(e,n){var t=[],r="",i=0;for(r in e)o.call(e,r)&&(t[i]=n(r,e[r]),i+=1);return t}var o=Object.prototype.hasOwnProperty;n.exports=r},{}],4:[function(e,n,t){function r(e,n,t){n||(n=0),"undefined"==typeof t&&(t=e?e.length:0);for(var r=-1,o=t-n||0,i=Array(o<0?0:o);++r<o;)i[r]=e[n+r];return i}n.exports=r},{}],5:[function(e,n,t){n.exports={exists:"undefined"!=typeof window.performance&&window.performance.timing&&"undefined"!=typeof window.performance.timing.navigationStart}},{}],ee:[function(e,n,t){function r(){}function o(e){function n(e){return e&&e instanceof r?e:e?f(e,u,i):i()}function t(t,r,o,i){if(!d.aborted||i){e&&e(t,r,o);for(var a=n(o),u=v(t),f=u.length,c=0;c<f;c++)u[c].apply(a,r);var p=s[y[t]];return p&&p.push([b,t,r,a]),a}}function l(e,n){h[e]=v(e).concat(n)}function m(e,n){var t=h[e];if(t)for(var r=0;r<t.length;r++)t[r]===n&&t.splice(r,1)}function v(e){return h[e]||[]}function g(e){return p[e]=p[e]||o(t)}function w(e,n){c(e,function(e,t){n=n||"feature",y[t]=n,n in s||(s[n]=[])})}var h={},y={},b={on:l,addEventListener:l,removeEventListener:m,emit:t,get:g,listeners:v,context:n,buffer:w,abort:a,aborted:!1};return b}function i(){return new r}function a(){(s.api||s.feature)&&(d.aborted=!0,s=d.backlog={})}var u="nr@context",f=e("gos"),c=e(3),s={},p={},d=n.exports=o();d.backlog=s},{}],gos:[function(e,n,t){function r(e,n,t){if(o.call(e,n))return e[n];var r=t();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(e,n,{value:r,writable:!0,enumerable:!1}),r}catch(i){}return e[n]=r,r}var o=Object.prototype.hasOwnProperty;n.exports=r},{}],handle:[function(e,n,t){function r(e,n,t,r){o.buffer([e],r),o.emit(e,n,t)}var o=e("ee").get("handle");n.exports=r,r.ee=o},{}],id:[function(e,n,t){function r(e){var n=typeof e;return!e||"object"!==n&&"function"!==n?-1:e===window?0:a(e,i,function(){return o++})}var o=1,i="nr@id",a=e("gos");n.exports=r},{}],loader:[function(e,n,t){function r(){if(!E++){var e=x.info=NREUM.info,n=l.getElementsByTagName("script")[0];if(setTimeout(s.abort,3e4),!(e&&e.licenseKey&&e.applicationID&&n))return s.abort();c(y,function(n,t){e[n]||(e[n]=t)}),f("mark",["onload",a()+x.offset],null,"api");var t=l.createElement("script");t.src="https://"+e.agent,n.parentNode.insertBefore(t,n)}}function o(){"complete"===l.readyState&&i()}function i(){f("mark",["domContent",a()+x.offset],null,"api")}function a(){return O.exists&&performance.now?Math.round(performance.now()):(u=Math.max((new Date).getTime(),u))-x.offset}var u=(new Date).getTime(),f=e("handle"),c=e(3),s=e("ee"),p=e(2),d=window,l=d.document,m="addEventListener",v="attachEvent",g=d.XMLHttpRequest,w=g&&g.prototype;NREUM.o={ST:setTimeout,SI:d.setImmediate,CT:clearTimeout,XHR:g,REQ:d.Request,EV:d.Event,PR:d.Promise,MO:d.MutationObserver};var h=""+location,y={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",agent:"js-agent.newrelic.com/nr-1118.min.js"},b=g&&w&&w[m]&&!/CriOS/.test(navigator.userAgent),x=n.exports={offset:u,now:a,origin:h,features:{},xhrWrappable:b,userAgent:p};e(1),l[m]?(l[m]("DOMContentLoaded",i,!1),d[m]("load",r,!1)):(l[v]("onreadystatechange",o),d[v]("onload",r)),f("mark",["firstbyte",u],null,"api");var E=0,O=e(5)},{}]},{},["loader"]);</script><script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","errorBeacon":"bam.nr-data.net","licenseKey":"eaeea54ab7","applicationID":"61695248","transactionName":"NgZTYEcEWEpWWkQKDg9Md0FbBkJQWFcfDhg+E0NbXwBVTUQXRgoEFhAfU1ARaVBZUEQKAA0KS1VBDFlXaF1RFwBbBFRAagxYUENQUQ8IGwJFXVoLaV1WTVE=","queueTime":0,"applicationTime":12,"agent":""}</script>\n\n    <title>List Maker With Superpowers - WorkFlowy</title>\n\n    <meta name="description" content="WorkFlowy is an organizational tool that makes life easier. It\'s a surprisingly powerful way to take notes, make lists, collaborate, brainstorm, plan and generally organize your brain.">\n    <link rel="shortcut icon" type="image/x-icon" href="/media/i/favicon.ico">\n    <meta name="ahrefs-site-verification" content="1e02598fc87129fdd8624212a90901b5a29fe287c590c9740af3c21f34784f42">\n\n    \n      <link href=\'https://fonts.googleapis.com/css?family=Open+Sans:300,400,700\' rel=\'stylesheet\' type=\'text/css\'>\n      \n      <link href="/media/css/landing.css" type="text/css" rel="stylesheet">\n      <link href=\'/media/css/landing--overrides.css\' rel=\'stylesheet\' type=\'text/css\'>\n      <link href=\'/media/css/inspire.css\' rel=\'stylesheet\' type=\'text/css\'>\n      \n      <!-- Touch device icons  -->\n      <link rel="apple-touch-icon" href="/media/i/workflowy-touch-icon-iphone.png" />\n      <link rel="apple-touch-icon" sizes="72x72" href="/media/i/workflowy-touch-icon-ipad.png" />\n      <link rel="apple-touch-icon" sizes="114x114" href="/media/i/workflowy-touch-icon-iphone4.png" />\n      <meta name="apple-mobile-web-app-status-bar-style" content="black" />\n      \n      <link rel="apple-touch-startup-image" href="/media/i/workflowy-startup-image.png">\n      \n    \n\n\n    \n\n    \n\n    <!-- FACEBOOK OPEN GRAPH API PROPERTIES - These seem to override\n     the properties passed in a feed story. -->\n    \n    <meta property="og:title" content="A simple way to organize your brain." />\n    <meta property="og:type" content="website" />\n    <meta property="og:url" content="https://workflowy.com" />\n    <meta property="og:site_name" content="WorkFlowy" />\n    <meta property="og:description" content="WorkFlowy is an incredible tool for thinking, writing, planning, organizing. Think like Einstein, and give it a shot.">\n    \n    <!-- END FACEBOOK OPEN GRAPH API PROPERTIES. -->\n\n    \n    \n\n    <script src="/media/js/jquery-1.5.1.min.js" type="text/javascript" ></script>\n\n    <script type="text/javascript">\n      var _gaq = _gaq || [];\n      _gaq.push([\'_setAccount\', \'UA-11472180-1\']);\n\n      _gaq.push([\'_trackPageview\']);\n\n      (function() {\n      var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true;\n      ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\';\n      var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s);\n      })();\n    </script>\n\n    <script type="text/javascript">\n  (function(e,t){var n=e.amplitude||{_q:[],_iq:{}};var r=t.createElement("script");r.type="text/javascript";r.async=true;r.src="https://cdn.amplitude.com/libs/amplitude-4.1.1-min.gz.js";r.onload=function(){if(e.amplitude.runQueuedFunctions){e.amplitude.runQueuedFunctions()}else{console.log("[Amplitude] Error: could not load SDK")}};var i=t.getElementsByTagName("script")[0];i.parentNode.insertBefore(r,i);function s(e,t){e.prototype[t]=function(){this._q.push([t].concat(Array.prototype.slice.call(arguments,0)));return this}}var o=function(){this._q=[];return this};var a=["add","append","clearAll","prepend","set","setOnce","unset"];for(var u=0;u<a.length;u++){s(o,a[u])}n.Identify=o;var c=function(){this._q=[];return this};var l=["setProductId","setQuantity","setPrice","setRevenueType","setEventProperties"];for(var p=0;p<l.length;p++){s(c,l[p])}n.Revenue=c;var d=["init","logEvent","logRevenue","setUserId","setUserProperties","setOptOut","setVersionName","setDomain","setDeviceId","setGlobalUserProperties","identify","clearUserPropertie","setGroup","logRevenueV2","regenerateDeviceId","logEventWithTimestamp","logEventWithGroups","setSessionId"];function v(e){function t(t){e[t]=function(){e._q.push([t].concat(Array.prototype.slice.call(arguments,0)))}}for(var n=0;n<d.length;n++){t(d[n])}}v(n);n.getInstance=function(e){e=(!e||e.length===0?"$default_instance":e).toLowerCase();if(!n._iq.hasOwnProperty(e)){n._iq[e]={_q:[]};v(n._iq[e])}return n._iq[e]};e.amplitude=n})(window,document);\n\n  amplitude.getInstance().init("b901558d7845aca815d2b136a5bc469b",\n      null,\n      { \'includeUtm\': true, \'deviceId\': \'a83d8eaa-f532-4940-8bcb-f52a527adfa3\', includeReferrer: true, includeGclid: true });\n</script>\n\n    <script type="text/javascript">\n      var amplitudeProperties = {};\n      \n      \n      \n    </script>\n\n    \n\n\n    \n    \n\n  </head>\n  <body class="\n    login\n">\n\n    \n    \n    \n\n\n    \n    <div class="header-bar">\n      <a href="/"><img class="logo--top" src="/media/i/wf-icon-logo-28x28.png" /></a>\n      \n      <a class="button--top-right button" href="/login">Login</a>\n      \n    </div>\n    \n\n    \n\n<h2>The page you\'re looking for doesn\'t exist.</h2>\n\n<p>\nGo to the <a  href="/">home page</a>.\n</p>\n\n\n\n\n    \n      <div id="bottomLinks">\n        <a href="https://blog.workflowy.com" target="_blank">Blog</a>\n        <a href="https://twitter.com/workflowy" target="_blank">Twitter</a>\n        <a href="https://workflowy.zendesk.com" target="_blank">Help</a>\n        <a href="https://status.workflowy.com" target="_blank">System Status</a>\n        <a href="/privacy/" target="_blank">Privacy</a>\n      </div>\n    \n\n  </body>\n</html>\n'`
